version: '3'
services:
        
# MongoDB - Reactive Persistence
  mongo:
    build:
      context: .\ecommerce-webapp\docker\mongo
      dockerfile: Dockerfile
    image: "mongodb"
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    env_file:
      - .\ecommerce-webapp\docker\mongo\.env

  # The mongo-seed container is just for waiting until the main mongo container is done setting its replicaset up
  # and then initializing data.
  mongo-seed:
    build:
      context: .\ecommerce-webapp\docker\mongo_seed
      dockerfile: Dockerfile
    image: "mongodb_seed"
    hostname: mongo_seed
    # ping the main mongo instance relentlessly until the connection is ready, then wait, then run an initialize data script to populate data.
    command: bash -c "until mongo mongo:27017/fantasy_db; do echo 'Waiting for Mongo to be ready...'; sleep 1; done; sleep 3; mongo mongo:27017/fantasy_db init.js; "
    links:
      - mongo

    
  webapp:
    container_name: ecommerce-webapp
    build:
       context: .\ecommerce-webapp
       dockerfile: Dockerfile
    restart: always
    image: web-tag
    hostname: webHost
    depends_on:
      - mongo
    ports:
      - 8888:8080
    network_mode: bridge
    healthcheck:
      test: "exit 0"

  webapp-reactive:
    container_name: ecommerce-web-reactive
    build: .\ecommerce-web-reactive
    image: webreactive-tag
    hostname: webReactiveHost
    depends_on:
      - webapp
    network_mode: bridge
    restart: always
    ports:
      - 8887:8083
    healthcheck:
      test: "exit 0"
    environment:
      - MONGODB_HOST=mongo
         
  webapp-angular:
    container_name: ecommerce-web-angular
    network_mode: bridge
    build:
         context: .\ecommerce-webapp-angular
         dockerfile: Dockerfile
    image: webangular-tag
    hostname: webAngularHost
    depends_on:
      - webapp-reactive
    ports:
        - 4200:4200
     
               
volumes:
  mongodata:      
