apiVersion: skaffold/v2beta11
kind: Config
build:
  tagPolicy:
     sha256: {}      # etiqueta amb : latest
#    gitCommit: {}
  artifacts:
  - image: ecommerce-webapp-angular
    context: ecommerce-webapp-angular
#  - image: ecommerce-cqrs
#    context: ecommerce-cqrs
#    jib:
#      type: maven
  - image: ecommerce-webapp
    context: ecommerce-webapp
    jib:
      type: maven
  - image: ecommerce-web-reactive
    context: ecommerce-web-reactive
    jib:
      type: maven
  - image: ecommerce-config
    context: ecommerce-config
    jib:
      type: maven      
  local:      # https://skaffold.dev/docs/pipeline-stages/builders/
#      tryImportMissing: true
     push: false
#      useDockerCLI: true
#  cluster:      # GCR
deploy:
  kubectl:
    manifests:
      - k8s/*    # arquitectura
      - istio/ecommerce.yaml
      - networking/ecommerce-gateway.yaml      
#      - ecommerce-webapp-angular/kubernetes/*
##      - ecommerce-cqrs/kubernetes/*
#      - ecommerce-webapp/kubernetes/*
#      - ecommerce-web-reactive/kubernetes/*

    
    

