apiVersion: v1
kind: Service
metadata:
  name: ecommerce-webapp-service
  labels:
    app: ecommerce-webapp
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: ecommerce-webapp
  selector:
    app: ecommerce-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-webapp
  labels:
    app: ecommerce-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-webapp
  template:
    metadata:
      labels:
        app: ecommerce-webapp
    spec:
      containers:
      - name: ecommerce-webapp
        image: ecommerce-webapp
        ports:
        - containerPort: 8080
          name: http   
        env:
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database-name
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password

    

