apiVersion: v1
kind: Service
metadata:
  name: ecommerce-webapp-angular
  namespace: default
spec:
  selector:
    app: ecommerce-webapp-angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80