apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-example
data:
  application.properties: |-
    myconfig.properties1=Config 1 Updated
    myconfig.properties2=Config 2
    myconfig.subconfig1.properties1=Sub config 1 property 1
    myconfig.subconfig1.properties2=Sub config 1 property 2
    myconfig.subconfig2.properties1=Sub config 2 property 1
    myconfig.subconfig2.properties2=Sub config 2 property 2
    
    
    # apunta al service
# Docker/Kubernetes
#spring.data.mongodb.host=mongodb

# Desenvolupament/SpringBoot  
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=fantasy_db