apiVersion: v1
kind: Pod
metadata:
  name: ecommerce-web-reactive
spec:
  hostNetwork: true
  containers:
  - name: ecommerce-web-reactive
    image: degloba/ecommerce-web-reactive:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8082
      hostPort: 8082
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
  imagePullSecrets:
    - name: myregistrykey