# Spring properties
# http://www.robertocrespo.net/kaizen/como-construir-microservicios-con-spring-boot/
spring:
  application:
     name: ecommerce-web-reactive-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
                             # Template location for this application only

  cloud:
    config:
      enabled: true
    kubernetes:
      discovery-server-url : kkkkkkk      
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8088/}   # where the config-service is running
    
    
    
# Discovery Server Access
#eureka:
#   client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/

# HTTP Server
#server:
  port: 1111   # HTTP (Tomcat) port
  
  